services:
  - type: web
    name: my-profile-server-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 20.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: BASE_URL
        value: https://my-profile-server-api.onrender.com
      - key: API_URL
        value: https://my-profile-server-api.onrender.com
      - key: CLIENT_URL
        value: https://my-profile-client.onrender.com
      - key: APP_NAME
        value: My Profile
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRATION
        value: 15m
      - key: JWT_REFRESH_EXPIRATION
        value: 1d
      - key: COOKIE_SECRET
        sync: false
      - key: SSL_ENABLED
        value: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_SERVICE
        value: gmail
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: TEXTBELT_API_KEYS
        sync: false
      - key: FORCE_DEV_SMS
        value: false
    healthCheckPath: /api/auth/healthcheck
